### PR TITLE
Feature/maven

### PR DESCRIPTION
**Pull request by Eernie**

### CODE REVIEW

**Comment by mayuso** [comment]
Thanks for helping me out with this. Just a quick question, I see you use reference to javaML and to 1.0 version (I´m new to maven, so I might be mistaken). Do I need to add reference to Apache POI and change version to current? (0.1.0 (soon 0.2.0))

**Comment by mayuso** [comment]
Oh, I now saw references to POI too, sorry.

**Comment by Eernie** [comment]
No problem. If completly new to maven maybe you should have a look at this: https://maven.apache.org/guides/getting-started/maven-in-five-minutes.html

And for releasing in the feature : 
http://central.stage.sonatype.org/pages/apache-maven.html

**Comment by mayuso** [comment]
Thank you! I will right now :)

**Comment by mayuso** [comment]
It´s actually a lot harder than I expected as a Gradle user xD Next release (0.2.0) will have all configured correctly. I expect to have it all done on the 22nd of january. (Next friday).

**Pull request merged**
